<?php
$z[0]=Array("global","",154,180);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='curr'\":@me=\"\";",472,560);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n",584,778);
$z[2][4]['type']="top";
$z[2][4]['row']="8";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='curr'>~typename~</a> </li>";

?>