<?php
$z[0]=Array("global","",302,328);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",369,396);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",434,464);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",1087,1122);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n        <li><a ><img src=\"[field:litpic /]\" alt=\"[field:title /]\" width=\"1000\" height=\"539\" /></a></li>\r\n",2789,2937);
$z[4][4]['typeid']="23";
$z[5]=Array("channel"," <li><a href=\"[field:typelink/]\">[field:typename/]</a></li> ",3327,3438);
$z[5][4]['type']="sun";
$z[5][4]['typeid']="4";
$z[6]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\"title=\"[field:title /]\" ><img src=\"[field:litpic /]\" alt=\"[field:title /]\" />\r\n            <p>[field:title /]</p>\r\n            </a></li>\r\n",3776,4005);
$z[6][4]['typeid']="4";
$z[6][4]['row']="10";
$z[7]=Array("sql","\r\n      [field:content function='cn_substr(html2text(@me),450)'/]\r\n",4519,4656);
$z[7][4]['sql']="Select content from #@__arctype where id=2";
$z[8]=Array("arclist","\r\n           <li><span>[[field:pubdate function=\"GetDateMK(@me)\"/]]</span><a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n",4924,5124);
$z[8][4]['typeid']="15";
$z[8][4]['row']="5";
$z[9]=Array("include","",5198,5235);
$z[9][4]['filename']="footer.htm";
$z[10]=Array("flink","\r\n        <li>[field:link /]</li> ",5390,5499);
$z[10][4]['row']="24";
$z[10][4]['type']="text";
$z[10][4]['titlelen']="26";
$z[10][4]['linktype']="2";
$z[11]=Array("include","",5638,5671);
$z[11][4]['filename']="qq.htm";

?>