<?php
$z[0]=Array("field","",113,159);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopid(@me)";
$z[1]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",273,412);
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n          ",639,791);
$z[2][4]['row']="6";
$z[2][4]['typeid']="15";

?>